name: 'Commit Message Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Commit Type
        uses: tim-actions/commit-message-checker-with-regex@master
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '\[[^]]+\] .+$'
          flags: 'gm'
          error: 'Your first line has to contain a commit type like "[BUGFIX]".'
      - name: Check Line Length
        if: succeeded() || failed()
        uses: tim-actions/commit-message-checker-with-regex@master
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '^[^#].{74}'
          error: 'The maximum line length of 74 characters is exceeded.'
      - name: Check for Resolves / Fixes
        if: succeeded() || failed()
        uses: tim-actions/commit-message-checker-with-regex@master
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '^.+(Resolves|Fixes): \#[0-9]+$'
          error: 'You need at least one "Resolves|Fixes: #<issue number>" line.'
