name: 'Commit Message Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Commit Type
        uses: tim-actions/commit-message-checker-with-regex@master
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '\[[^]]+\] .+$'
          flags: 'gm'
          error: 'Your first line has to contain a commit type like "[BUGFIX]".'
      - name: Check Line Length
        if: ${{ success() || failure() }}
        uses: tim-actions/commit-message-checker-with-regex@master
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '^[^#].{74}'
          error: 'The maximum line length of 74 characters is exceeded.'
      - name: Check for Resolves / Fixes
        if: ${{ success() || failure() }}
        uses: tim-actions/commit-message-checker-with-regex@master
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '\\s*Fixes\\s*:?\\s*(#\\d+|github\.com\/kata-containers\/[a-z-.]*#\\d+)'
          error: 'No "Fixes" found'

      - name: Error Tips
        if: ${{ failure() }}
        run: echo "::debug::checkcommits failed. See the document below for help on formatting\ncommits for the project.\n\nhttps://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format"
