name: WIP
on:
  pull_request:
    types:
      - labeled
      - unlabeled
jobs:
  merge:
    runs-on: ubuntu-latest
    name: WIP Check
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@v0.2.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        labels: ""
        blocking-labels: do-not-merge, wip, rf
        checks: true
